### ISSUE TITLE
Improve sudo

### ISSUE THREAD

**Issue by LaszloGombos** [ivanilves/xiringuito#57]
sudo: no tty present and no askpass program specified.

Can you explain/improve this error message ?

**Comment by LaszloGombos** [comment]
Full log :-)

~/xiringuito ./xiringuito IP 10.0.0.0/8 192.168.0.0/16
[ sudo check ]
TUNNEL ID: 42 (local: 42)
sudo: no tty present and no askpass program specified
sudo: no tty present and no askpass program specified
sudo: no tty present and no askpass program specified
sudo: no tty present and no askpass program specified
Terminated

**Comment by LaszloGombos** [comment]
export SUDO_ASKPASS="myaskpass.sh"
makes no difference for me. Seems sudo is called without a tty attached ?

**Comment by ivanilves** [comment]
Hi @gombos 

Thanks for opening an issue, I confirm this is the real problem. :muscle: 

I think I got it: the SSH server you connect to has sudo with password and due to way we work with sudo on the server side now, it fails :weary: We need to fix it ASAP I think as long as this is a pretty frustrating issue.

**Comment by ivanilves** [comment]
Hey @gombos could you try if it works for you https://github.com/ivanilves/xiringuito/pull/58 ? Thanks!

**Comment by ivanilves** [comment]
Basically the bug is fixed, but we wait for comments here if any, maybe we will need to make sudo permissions more granular :wink:

**Comment by ivanilves** [comment]
We consider this solved now, right?
